# makes a hash of the form:
# {"country name" => {"coords" => [x,y], "city name" => [x,y]}}
# for the US, the state is substituted for United States.
# right now this is a big procedural kludge

# highest level hash: countries
countries = Hash.new{|h,k| h[k] = Hash.new}

coutries = {}
t = File.read('countries.txt')
t.each_line do |line|
  cleaned = line.gsub("\n","").gsub("\t","")
  split_line = cleaned.split(",")
  key = split_line[0].to_s.strip
  value = []
  value << split_line[1].gsub(" ","").to_f
  value << split_line[2].gsub(" ","").to_f
  h = {}
  h["coords"] = value
  countries[key] = h
end

us_states = {}
tx = File.read('us-states.txt')
tx.each_line do |line|
  cleaned = line.gsub("\n","").gsub("\t","")
  split_line = cleaned.split(",")
  key = split_line[0].to_s.strip
  value = []
  value << split_line[1].gsub(" ","").to_f
  value << split_line[2].gsub(" ","").to_f
  us_states[key] = value
end

text = File.read('cities.txt')
text.each_line do |line|
  cleaned = line.gsub("\n","").gsub("\t","")
  split_line = cleaned.split(",")
  key = split_line[0].to_s.strip
  if key == "United States"
    key = split_line[1].to_s.strip
    countries[key]["coords"] = us_states[key]
  end
  value = []
  value << split_line[-2].to_f
  value << split_line[-1].to_f
  city = {}
  city_name = split_line[2].to_s.strip
  city[city_name] = value
  countries[key][city_name] = value
end

puts "#autogenerated on "+Time.now.to_s
puts "class FBLocation"
puts "  attr_accessor :location_list"
puts "  def initialize"
puts "    @location_list = "+countries.to_s
puts "  end"
puts "end"
